language: python
python:
  - "2.7"
env:
  global:
  - PACIFICA_ROOT: /tmp/pacifica-core
script:
  - pylint --rcfile=pylintrc sphinx/*.py
  - make -C sphinx html
  - find -name '*.md' | grep -v 'node_modules' | xargs -n 1 -I '{}' /tmp/node.js/node-v4.4.7-linux-x64/bin/node ./node_modules/remark-cli/cli.js {} -u remark-lint --frail
# Handle git submodules yourself
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
 - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
 - git submodule update --init --recursive
 - git clone https://github.com/EMSL-MSC/pacifica.git /tmp/pacifica-core
 - sed -i 's/git@github.com:/https:\/\/github.com\//' /tmp/pacifica-core/.gitmodules
 - pushd /tmp/pacifica-core
 - git submodule update --init --recursive
 - cd ..
 - mkdir node.js
 - cd node.js
 - curl -L https://nodejs.org/dist/v4.4.7/node-v4.4.7-linux-x64.tar.xz | tar -xJf -
 - popd
 - /tmp/node.js/node-v4.4.7-linux-x64/bin/npm install remark-cli remark-lint
